### PR TITLE
Front end fixes

### PR DESCRIPTION
**Pull request by ErickSch**
- Chatbot scroll
- Quizes container shadows
- Navbar

### CODE REVIEW

**Comment by mohes7489** [comment]
the "+" button in the sidebar of the chatbot page is not properly showing in small screen
+ button

**Comment by mohes7489** [comment]
the login and sign up buttons are out of the navbar border, when it displayed is smaller screen

buttons

**Comment by mohes7489** [comment]
the app is crashing if I go to the login or the register pages .. the AppContext shouldn't be removed from layout.tsx... it should wrap the entire application

**Comment by gajuuu** [comment]
Chat scroll does not work for me.
The other two functions looks fine.

**Review by gajuuu — APPROVED** [review]

**Pull request closed without merging**
