### PR TITLE
TASK 69 Connect old conversation frontend and backend

### PR DESCRIPTION
**Pull request by roosavihlman**
Ticket https://github.com/orgs/APUOPE-RE/projects/3/views/1?pane=issue&itemId=87298533&issue=APUOPE-RE%7Cfrontend%7C69

Finalized endpoint call from frontend to backend and made Conversation-component, which lists all conversations that user has had.

### CODE REVIEW

**Comment by mohes7489** [comment]
the conversation history is over the the chatbot and the "+"  sign

**Comment by mohes7489** [comment]
after choosing a conversation from the conversation history, I can not continue talking with the llm? is that on purpose or what?

**Comment by roosavihlman** [comment]
> after choosing a conversation from the conversation history, I can not continue talking with the llm? is that on purpose or what?

Yes, this we agreed together that user cannot continue old conversation. It is nice to have feature but not prio. Continuing old conversation would need that we provide the whole conversation to LLM or some highlights. Therefore, we should first implement the most wantes features first but it is good that user can atleast view the old conversations.

**Comment by roosavihlman** [comment]
> 
> the conversation history is over the the chatbot and the "+" sign

Edited stylings to fix this :heavy_check_mark: 
image

**Review by mohes7489 — APPROVED** [review]

**Pull request merged**
