### PR TITLE
TASK 96 implement the responsible navbar

### PR DESCRIPTION
**Pull request by gajuuu**
#96

- Implemented the responsible navbar for mobile
- Changed the menu in the order of Chatbot, Quiz Maker, and Previous Quizzes
- Changed so that these menus are not displayed in the navbar before login

### CODE REVIEW

**Comment by mohes7489** [comment]
the implementation looks clean. one thing, now you are hiding the chat Bot and the quiz parts until the user is authenticated (logged in). but the user can go, for example, to the chat bot if he/she click on the logo, or even simply write "previous-quizzes" or "quiz" in the URL. the better and more secure approach is to let the backend handle that logic.
another thing, if you want to do that, for better user experience, now if I click on the sing in picture, it open the the menu, and if I click it again it will not close it. if you can, for better user experience, make it close if the user click it again.

**Comment by gajuuu** [comment]
Thank you for your comment. I will hide the home link to Chatbot (from the logo image) too. Then I will create a ticket for backend and share it in Telegram. 
The other one, I will also add this function to close the menu!

**Comment by gajuuu** [comment]
done fixing

**Comment by gajuuu** [comment]
fixing done

**Review by roosavihlman — APPROVED** [review]

**Pull request merged**
